version: '2.3'
volumes:
  database:

x-network: &cap-add
  cap_add:
    - NET_ADMIN
x-consumer: &consumer
  image: localbuild/client:latest
  restart: always
  depends_on:
    - prometheus
    - grafana
  volumes:
    - ./$CONFIG_FILE:/tmp/client.config
    - ./monitoring_configs/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar
    - ./monitoring_configs/jmx-exporter/kafka_client.yml:/usr/share/jmx-exporter/kafka_client.yml
    - ./:/tmp/java/
  environment:
    MAVEN_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/kafka_client.yml
  command: >
    bash -c "sleep 15 &&
    mvn compile -f /tmp/java/
    &&  mvn -q -f /tmp/java/pom.xml exec:java -Dexec.mainClass=\"io.confluent.examples.clients.cloud.ConsumerExample\" -Dexec.args=\"/tmp/client.config demo-topic-1\""

services:
  node-exporter:
    image: prom/node-exporter:v0.18.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^(aufs|proc|nsfs|shm|cgroup|tmpfs|binfmt_misc|debugfs|devpts|fusectl|hugetlbfs|fuse.lxcfs|mqueue|pstore|securityfs|sysfs|autofs|devtmpfs|configfs)"

  ccloud-exporter:
    image: dabz/ccloudexporter:latest
    container_name: ccloud-exporter
    hostname: ccloud-exporter
    restart: always
    environment:
      - CCLOUD_API_KEY=$METRICS_API_KEY
      - CCLOUD_API_SECRET=$METRICS_API_SECRET
      - CCLOUD_CLUSTER=$CLOUD_CLUSTER

  prometheus:
    image: prom/prometheus:v2.24.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring_configs/prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana
    environment:
      - "GF_INSTALL_PLUGINS=grafana-piechart-panel"
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    ports:
      - 3000:3000
    volumes:
      - ./monitoring_configs/grafana/provisioning/:/etc/grafana/provisioning/

  producer:
    image: localbuild/client:latest
    restart: always
    depends_on:
      - prometheus
      - grafana
    hostname: producer
    container_name: producer
    volumes:
      - ./$CONFIG_FILE:/tmp/client.config
      - ./monitoring_configs/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar
      - ./monitoring_configs/jmx-exporter/kafka_client.yml:/usr/share/jmx-exporter/kafka_client.yml
      - ./:/tmp/java/
    ports:
      - 1234:1234
    environment:
      MAVEN_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/kafka_client.yml
    command: >
      bash -c "mvn clean compile -f /tmp/java/
      &&  mvn -q -f /tmp/java/pom.xml exec:java -Dexec.mainClass=\"io.confluent.examples.clients.cloud.ProducerExample\" -Dexec.args=\"/tmp/client.config demo-topic-1\""
    <<: *cap-add

  consumer-1:
    <<: *consumer
    hostname: consumer-1
    container_name: consumer-1
    ports:
      - 1237:1234
    <<: *cap-add

  consumer-2:
    <<: *consumer
    hostname: consumer-2
    container_name: consumer-2
    ports:
      - 1236:1234
    <<: *cap-add
